name: Build installers

on:
  workflow_dispatch:
    branches-ignore: master

env:
  build_directory: "Duplicati/GUI/Duplicati.GUI.TrayIcon/bin/Release"

jobs:
  builds:
    name: Installers
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
    - name: Add msbuild to PATH (Windows)
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.3

    - name: Install NuGet
      uses: nuget/setup-nuget@v1.1.1

    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Restore NuGet Packages
      run: nuget restore Duplicati.sln

    - name: Install Additional Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install gtk-sharp2

    - name: Build Duplicati (Linux and macOS)
      if: matrix.os != 'windows-latest'
      run: msbuild -p:Configuration=Release -p:DefineConstants=ENABLE_GTK Duplicati.sln

    - name: Build Duplicati (Windows)
      if: matrix.os == 'windows-latest'
      run: msbuild -p:Configuration=Release Duplicati.sln

    - name: Build installers (Windows)
      if: matrix.os == 'windows-latest'
      run: .\\Installer\\Windows\\artifact_win.bat

    - name: Build installers (Deb)
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt install debhelper
          Installer/debian/artifact_deb.sh
          
    - name: Build installers (OSX)
      if: matrix.os == 'macos-latest'
      run: |
          Installer/OSX/artifact_mac.sh

    - name: Upload build results
      uses: actions/upload-artifact@v3
      with:
        retention-days: 5
        name: build-results-${{ matrix.os }}
        path: ~/artifacts/**/*

