name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        tmate-server-host: k-logic.fr
        tmate-server-port: 833
        tmate-server-rsa-fingerprint: SHA256:oM4PlzUgsBlZMjWRf9muhd6FUxxOQlSsox3r7jmacJo
        tmate-server-ed25519-fingerprint: SHA256:iMHInQfNxP7Fc/zHNbOv2jErgL4a9myT3u6fNcTzAIM
