name: Parameterized tests

on:
  workflow_dispatch:
    inputs:
      operating_system:
        type: choice              
        description: 'runner os'
        required: true
        options:
        - ubuntu-latest
        - windows-latest
        - macos-latest
      test_to_run:
        description: 'test to run'
        required: true
      repeat_factor:
        description: 'number of times to run the test'
        required: true
        default: 1

env:
  build_directory: "Duplicati/GUI/Duplicati.GUI.TrayIcon/bin/Release"

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ${{ inputs.operating_system }}
    strategy:
      fail-fast: false

    steps:
            
    - name: Add msbuild to PATH (Windows)
      if: inputs.operating_system == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.3

    - name: Install NuGet
      uses: nuget/setup-nuget@v1.1.1

    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Restore NuGet Packages
      run: nuget restore Duplicati.sln

    - name: Install Additional Dependencies
      if: inputs.operating_system == 'ubuntu-latest'
      run: sudo apt-get install gtk-sharp2

    - name: Build Duplicati (Linux)
      if: inputs.operating_system == 'ubuntu-latest'
      run: msbuild -p:Configuration=Release -p:DefineConstants=ENABLE_GTK Duplicati.sln

    - name: Build Duplicati (macOS)
      if: inputs.operating_system == 'macos-latest'
      run: msbuild -p:Configuration=Release Duplicati.sln

    - name: Build Duplicati (Windows)
      if: inputs.operating_system == 'windows-latest'
      run: msbuild -p:Configuration=Release Duplicati.sln

    - name: Run Unit Tests (Linux and macOS)
      if: inputs.operating_system != 'windows-latest'
      run: |
        nuget install NUnit.Runners -Version 3.12.0 -OutputDirectory nunit
        mono nunit/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe Duplicati/UnitTest/bin/Release/Duplicati.UnitTest.dll --test=${{ inputs.test_to_run }}

    - name: Run Unit Tests (Windows)
      if: inputs.operating_system == 'windows-latest'
      run: |
        $tot=${{ inputs.repeat_factor }}
        $p=1
        $sep="----------------------------------------------------------------"
        nuget install NUnit.Runners -Version 3.12.0 -OutputDirectory nunit
        do { nunit/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe Duplicati/UnitTest/bin/Release/Duplicati.UnitTest.dll /test:${{ inputs.test_to_run }} ; echo $sep" ("$p"/"$tot")"  ; $p=$p+1 } until ( $p -gt $tot )

