name: UItests

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  build_directory: "Duplicati/GUI/Duplicati.GUI.TrayIcon/bin/Release"

jobs:
  ui_tests:
    name: UI tests
    runs-on: ubuntu-latest

    # Some of these steps duplicate those in the unit_tests job above.  This
    # can be cleaned up using a composite run steps action once it supports
    # what we need (https://github.com/actions/runner/issues/646).
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Install NuGet
      uses: nuget/setup-nuget@v1.1.1

    - name: Restore NuGet Packages
      run: nuget restore Duplicati.sln

    - name: Install Additional Dependencies
      run: sudo apt-get install gtk-sharp2

    - name: Build Duplicati
      run: msbuild -p:Configuration=Release -p:DefineConstants=ENABLE_GTK Duplicati.sln

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip3 install selenium
        pip3 install --upgrade urllib3

    - name: Run UI tests
      run: |
        cp -r Duplicati/Server/webroot "${{ env.build_directory }}"/webroot
        mono "${{ env.build_directory }}"/Duplicati.Server.exe &
        python3 guiTests/guiTest.py
